# Generated by Django 6.0.1 on 2026-01-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_exam_end_time_remove_exam_is_scheduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassignment',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
