# Generated by Django 6.0.1 on 2026-01-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examassignment_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassignment',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
    ]
